# Generated by Django 4.1.1 on 2022-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_property_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='info',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
